### ISSUE TITLE
Processed vote result needs a reference to raw vote record

### ISSUE THREAD

**Issue by ahulab** [LoveShack-Inc/represent#15]
The `processed_row_result` table includes no reference to the `raw_vote_object` record that it came from. Breaking this link after processing the record makes it impossible to figure out which document it came from without re-processing the records. That means we can't currently show a vote object pdf, and then also show it's processed results

We could do something hacky and try to find the `billNumber` in the `sourceUrl` of the `raw_vote_object`, but that's really not how we should be doing it, it need a foreign key reference instead

**Comment by dalton-b** [comment]
Is this effectively already done? I assume that's what "linked a pull request that will close this issue" means

**Comment by ahulab** [comment]
Yeah this one will be done if my PR gets merged. It's working on my Pr branch and is currently deployed

**Comment by ahulab** [comment]
One problem though, is that it makes the assumption that every vote result will have a raw vote object associated with it, but depending on how we source results for other states (if that ever happens), that might not be the case. Like, if we just get results from an api endpoint, then we wouldn't even need an entry in the raw vote object table

**Comment by dalton-b** [comment]
I'm fine with that for now, if you're fine with it
