### ISSUE TITLE
Handle different types of vote PDFs

### ISSUE THREAD

**Issue by dalton-b** [LoveShack-Inc/represent#4]
There are (apparently) multiple different types of vote documents, and we're only equipped to handle a very specific one. Links below:

We can handle this:
[Good PDF](https://www.cga.ct.gov/2020/VOTE/s/pdf/2020SV-00013-R00SJ00014-SV.pdf)

Not this:
[Bad PDF](https://www.cga.ct.gov/2020/TS/h/pdf/2020HB-05333-R00KID-CV57-TS.pdf)

There may be other types of vote documents as well, I'll keep an eye out and update here

**Comment by dalton-b** [comment]
Here's another type of PDF:

![image](https://user-images.githubusercontent.com/25960448/99615734-e9b4ef80-29e9-11eb-9a51-ff7a0c5a2bd6.png)

**Comment by ahulab** [comment]
This one is handled now. But there are still others that we don't currently handle properly. You can find them pretty easily in the UI now by showing unprocessed records and clicking on stuff until you find a vote format we don't handle

**Comment by dalton-b** [comment]
Ok great, I'll work on it this week
